/var/spool/slurm/d/job637321/slurm_script: line 9: cd: too many arguments
Traceback (most recent call last):
  File "WaveForM_trend_res.py", line 966, in <module>
    train_loss = train(model, train_loader, optimizer, criterion, device)
  File "WaveForM_trend_res.py", line 837, in train
    outputs = model(seq_x)
  File "/home/choi/conda/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/choi/conda/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "WaveForM_trend_res.py", line 811, in forward
    pred_out_res = self.backbone_res(res)
  File "/home/choi/conda/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/choi/conda/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "WaveForM_trend_res.py", line 731, in forward
    coefs_new = self.model(coefs)
  File "WaveForM_trend_res.py", line 717, in model
    new_coef = net(coef.permute(0,2,1).unsqueeze(-1))
  File "/home/choi/conda/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/choi/conda/anaconda3/envs/pytorchenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "WaveForM_trend_res.py", line 551, in forward
    assert (
AssertionError: Input sequence length not equal to preset sequence length.
srun: error: gpu-023: task 0: Exited with exit code 1
